dist: trusty
sudo: false
language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libxerces-c-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - gcc -v && g++ -v && cmake --version
  - make -j2
